### PR TITLE
Fixes for NuGet packaging

### PR DESCRIPTION
**Pull request by jamesqo**
The pull request as you asked for in #2.

Changes:

- Infrastructure
  - The DLL has been moved from `build/lib/` to `build/`.
  - Instead of using `xcopy` to copy the assembly into a bunch of different target frameworks, we can use NuGet's `<file src="..."` tag to do this for us without having to have an actual `lib/` directory. See the [nuspec reference](http://docs.nuget.org/Create/Nuspec-Reference#specifying-files-to-include-in-the-package) for more on this.
  - Removed the entire `lib/` directory, as it is no longer needed.
- Target Platforms
  - `net` and `netcore` are not valid target frameworks (see [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/FrameworkConstants.cs#L70) for a list of all frameworks). Removed that.
  - `netcore45` is equivalent to `win8`, which we already target in the portable profile, so remove that.
  - Using the library will *not* work on .NET Framework 1.1, since we [hard-code](https://github.com/DotNetCross/Memory.Unsafe/blob/master/il/DotNetCross.Memory.Unsafe.il#L52) a reference to the `System.Runtime` façade assembly into the IL. Façade assemblies were only introduced to support PCLs around .NET 4.5, so referencing the package won't work on platforms older than that.
    - Since we already target .NET 4.5 via the portable profile, we can remove `net11` entirely.
  - Same goes for the portable profile; the oldest PCL that supports `System.Runtime` is Profile259, or `portable-net45+netcore45+wpa81+wp8`. I've changed the portable target framework to that.
    - This also means people will be able to use the package from Windows Phone 8.1.
  - Explicitly targeting `dnxcore` is not needed, since it can consume Profile259 projects.
  - Added a dependency on the `System.Runtime` [NuGet package](https://www.nuget.org/packages/System.Runtime/4.0.0) for `dotnet`, and the `System.Runtime` framework assembly for the portable profile.

### CODE REVIEW

**Comment by jamesqo** [comment]
Since you said you weren't getting the notifications: @nietras

**Comment by nietras** [comment]
@jamesqo thank you very much, not the least for the thorough explanation. I'm working on it currently, and found an issue with the nuspec, the `<files>` had to be moved after `</metadata>`  for example.

Before pushing I wanted to be sure this fixed the issue in the unit tests project, but it does not. It still says the library does not support DNXCore... not sure what needs to be done to fix this. Tried adding `group targetFramework="DNXCore5.0">` to the nuspec but that did not help. I'm still struggling a lot with understand how to target the many different framework stuff even though I've read most blogs by say Oren Novotny on the subject.

**Comment by nietras** [comment]
@jamesqo Sigh. I give up. This whole .NET Core stuff never work. It still fails for the unit tests project. For whatever reason I cannot fathom since it has worked before. Is it just me, or do any of the .NET Core tools actually work or give sensible error messages? 

I've tried cloning most .NET core repos and none of them work out of the box. Not ever. Tried on multiple machines even. Still no luck, either restore gives errors or build gives errors or test run gives errors.

Anyway, if you have any ideas or hints on how to fix this I would appreciate it. A good link to someone describing in full detail how `project.json` configuration for multiple target frameworks etc. would also be appreciated.

**Comment by jamesqo** [comment]
Uh... the `project.json` pulls all of its dependencies from NuGet, so you have to upload the new version to NuGet before you can use it from the unit tests/benchmarks project. :smile:

**Comment by nietras** [comment]
No I made a local nuget folder that I then use as source. That is, I add it
to VS options. This way I can test the package before uploading.

**Comment by jamesqo** [comment]
Hmm, that's pretty strange then. I'll try cloning the repo again and testing for myself.

**Pull request merged**
