### PR TITLE
Remove references to the old package + tidy up the README

### PR DESCRIPTION
**Pull request by jamesqo**
I appreciated you taking the time to rename the old NuGet package for me, so I thought I'd return the favor and submit a pull request. I've removed all references to the old package name with the `.dll` suffix and also tidied up + added a few more samples to the README.

### CODE REVIEW

**Comment by nietras** [comment]
@jamesqo wow thanks very much, for some reason I did not get a notification about this. But looking at it now and will merge.

**Comment by jamesqo** [comment]
@nietras No problem, I enjoyed doing it haha :smile: I've also noticed a few issues with your `.nuspec` and NuGet target platforms, would be willing to accept a pull request for that as well?

**Comment by nietras** [comment]
I'm struggling with the merge right now, for some reason it won't accept the nuget package in the UnitTests project...

image

And yes! I've wanted to fix the nuspec and too many copies of the dll for some time, had been hoping that putting the `dll` in just `lib` would work cross-platform as advertised but it doesn't...

**Comment by nietras** [comment]
I've tried uninstalling/reinstalling the package but nope, doesn't work. I don't understand how it can end up with 0.2.1.since this isn't even part of the nuget feed anymore.

**Comment by jamesqo** [comment]
@nietras Have you tried closing the solution/deleting the `.vs` folder and reopening it? If not you could `rm -rf` the git repo and clone it again from GitHub. I was having a similar problem a while ago, and after re-cloning the repo it suddenly worked in Visual Studio.

**Comment by nietras** [comment]
Tried deleting `.vs` folder, but that didn't help. Anyway, I commitet the pull request merge anyway, since I didn't want to loose what I did, before recloning.

**Comment by nietras** [comment]
Recloning didn't work but at least it lost the `0.2.1` version. So I guess this is a new nuget package issue I didn't have before, so ... waiting for that pull request ;) We can make a version 0.2.3 then.

image

**Pull request merged**
